"""
Frappe Console Script — Warehouse Verification
Paste this into ERPNext System Console (/app/system-console) and run.

This script checks every warehouse name from your exported list against the live
tabWarehouse table and reports: existence, disabled status, group parent status,
parent warehouse, and whether the warehouse has any Stock Ledger Entry activity.
"""

# NOTE: Do NOT use "import frappe" — frappe is already available in System Console.
# Paste your full warehouse list here (one per line, or as a Python list)
warehouse_names = [
    "All Warehouses - KCL",
    "Finished Goods - KCL",
    "Goods In Transit - KCL",
    "Stores - KCL",
    "Work In Progress - KCL",
    "All Warehouses - VFL",
    "Admin - VFL",
    "Aqua - VFL",
    "Construction - VFL",
    "Fish Q - VFL",
    "In Transit - VFL",
    "3PL-AD-KBX 935V - VFL",
    "3PL-AD-KCX 482Y - VFL",
    "3PL-AD-KCY 928B - VFL",
    "3PL-AD-KCZ 039P - VFL",
    "3PL-AD-KCZ 239P - VFL",
    "3PL-AD-KCZ 466J - VFL",
    "3PL-AD-KCZ-233P - VFL",
    "3PL-AD-KDB 017Q - VFL",
    "3PL-AD-KDC 172F - VFL",
    "3PL-AD-KDE 116A - VFL",
    "3PL-AD-KDE 591K - VFL",
    "3PL-AD-KDE093V - VFL",
    "3PL-AD-KDH 233F - VFL",
    "3PL-AD-KDH 856D - VFL",
    "3PL-AD-KDR 385D - VFL",
    "3PL-CB-KDH 133V - VFL",
    "3PL-CF-KBN 562V - VFL",
    "3PL-CF-KBP 648J - VFL",
    "3PL-CF-KCP 907Q - VFL",
    "3PL-CF-KCT 296F - VFL",
    "3PL-CF-KCV 482J - VFL",
    "3PL-CF-KCV 844Y - VFL",
    "3PL-CF-KCW 023Z - VFL",
    "3PL-CF-KCX 062Z - VFL",
    "3PL-CF-KCZ 094L - VFL",
    "3PL-CF-KCZ 113N - VFL",
    "3PL-CF-KDB 186L - VFL",
    "3PL-CF-KDB 295H - VFL",
    "3PL-CF-KDB 648J - VFL",
    "3PL-CF-KDG 170L - VFL",
    "3PL-CF-KDJ 173C - VFL",
    "3PL-CF-KDJ 273N - VFL",
    "3PL-CF-KDM 206E - VFL",
    "3PL-CF-KDN 401N - VFL",
    "3PL-CF-KDQ 042Z - VFL",
    "3PL-CF-KDQ773Y - VFL",
    "3PL-CL- KCH 137B - VFL",
    "3PL-CL-KBM 301Y - VFL",
    "3PL-CL-KDP 931L - VFL",
    "3PL-CY-KDE 486P - VFL",
    "3PL-DF-KDC 992Y - VFL",
    "3PL-DF-KDE 523W - VFL",
    "3PL-DF-KDJ 301L - VFL",
    "3PL-DF-KDJ 646X - VFL",
    "3PL-FL-KAR 992E - VFL",
    "3PL-FL-KBK 712J - VFL",
    "3PL-FL-KBQ 573U - VFL",
    "3PL-FL-KBR 507Z - VFL",
    "3PL-FL-KBT 280L - VFL",
    "3PL-FL-KDE 750B - VFL",
    "3PL-FL-KDH 086Y - VFL",
    "3PL-FL-KDJ 093C - VFL",
    "3PL-FL-KDR 894A - VFL",
    "3PL-FR-KBZ 950X - VFL",
    "3PL-FR-KDA 626Y - VFL",
    "3PL-KAG-KBT 833K - VFL",
    "3PL-KAG-KDQ 856Z - VFL",
    "3PL-KIL-KDH 290H - VFL",
    "3PL-KIL-KDK 084Y - VFL",
    "3PL-KIL-KDK 096D - VFL",
    "3PL-PEEAL-KCD 513K - VFL",
    "3PL-PL-KCC 361G - VFL",
    "3PL-PL-KDP 467E - VFL",
    "3PL-PL-KDQ 112J - VFL",
    "3PL-SE-KDB 202Q - VFL",
    "3PL-SE-KDQ 251A - VFL",
    "3PL-SK- KDG 419F - VFL",
    "3PL-SK-KCX 021W - VFL",
    "3PL-SK-KDE 127R - VFL",
    "3PL-SK-KDG 330Y - VFL",
    "3PL-SK-KDH 293Z - VFL",
    "3PL-SK-KDJ 463C - VFL",
    "3PL-SK-KDN 014A - VFL",
    "3PL-SK-KDQ 294F - VFL",
    "3PL-SK-KDQ 411C - VFL",
    "3TPL-KIL-KCY 086P - VFL",
    "Chui 6.5Mt Kcn 042Y - VFL",
    "Duma 4.5Mt Kdc 106U - VFL",
    "Farasi 1.5Mt Kcq 045S - VFL",
    "In Transit Variance - VFL",
    "Kiboko 3.5Mt Kcs 559A - VFL",
    "Kifaru 13.5Mt Kcs 560A - VFL",
    "Mamba 2.8Mt Kcq 982Z - VFL",
    "Mwewe 3.5Mt Kct 213T - VFL",
    "Ndovu 28Mt Kcy 048N - VFL",
    "Nyati 28Mt KDP 369K-VLC",
    "NYATI 28MT KDP 396K-VLC",
    "RIDER - Brian - VFL",
    "Roo Truck - VFL",
    "Simba 13.5Mt Kct 466T - VFL",
    "Swara 4.5Mt Kdc 094U - VFL",
    "TPL-SK-KDE 127R - VFL",
    "Twiga 3.5Mt Kcs 561A - VFL",
    "3PL-CL-KDC 171Y - VFL",
    "3PL-FL-KCS 055Q - VFL",
    "3PL-CF-KBW 275A - VFL",
    "3PL- KIL - KCA 179J - VFL",
    "3PL- CL-KDH 038T - VFL",
    "3PL-SK-KCS 130S - VFL",
    "TAI 28MT KDS 422U  - VFL",
    "KOBE KDS 412X - VFL",
    "3PL-NEO-KCM 218F - VFL",
    "NQR81 BLUEPOWER TRUCK 1 - VFL",
    "NQR81 BLUEPOWER TRUCK 2 - VFL",
    "5MT KDU 084V  - VFL",
    "5MT KDU 086V - VFL",
    "Pweza 5Mt KDU 084V - VFL",
    "Skifoc 5T KDH 298R - VFL",
    "Paa 5Mt KDU 086V - VFL",
    "Mawenzi KDL 168G - VFL",
    "Toyota Hilux Z Edition (2022) (Black) - VFL",
    "TPL-KAI-5Mt KDR 358Y - VFL",
    "Skifoc 5MT KDA 864L - VFL",
    "TPL-KAI-5MT KDB 358Y - VFL",
    "Operations - VFL",
    "Farm Store - VFL",
    "Feeds Store - VFL",
    "Procurement - VFL",
    "Farm Procurement - VFL",
    "KLC Procurement - VFL",
    "MLC Procurement - VFL",
    "VLC Store Procurement - VFL",
    "Sales - VFL",
    "NBO - VFL",
    "Africa - VFL",
    "Free Area - VFL",
    "Free Area - VFL Spoilage",
    "Imara - VFL",
    "Imara - VFL Spoilage",
    "Kitengela - VFL",
    "Kitengela - VFL Spoilage",
    "Machakos - VFL",
    "Machakos - VFL Spoilage",
    "Mlolongo - VFL",
    "Mlolongo - VFL Spoilage",
    "Pipeline - VFL",
    "Pipeline - VFL Spoilage",
    "Shabab - VFL",
    "Shabab - VFL Spoilage",
    "Huruma - VFL",
    "Huruma - VFL Spoilage",
    "Ngara - VFL",
    "Buru Buru - VFL",
    "Dagoretti - VFL",
    "Yaya - VFL",
    "Bombolulu - VFL",
    "Antarctica - VFL",
    "Bombolulu - VFL Spoilage",
    "Buru Buru - VFL Spoilage",
    "Kangemi - VFL",
    "Kangemi - VFL Spoilage",
    "Keroka - VFL",
    "Keroka - VFL Spoilage",
    "Kibera - VFL",
    "Kibera - VFL Spoilage",
    "Nairobi West - VFL",
    "Nairobi West - VFL Spoilage",
    "Naivas Capital - VFL",
    "Satellite - VFL",
    "Satellite - VFL Spoilage",
    "Mathare - VFL Spoilage",
    "Mathare - VFL",
    "Naivas Capital - VFL Spoilage",
    "Kawangware - VFL",
    "Kawangware - VFL Spoilage",
    "Asia - VFL",
    "Garden Estate - VFL",
    "Garden Estate - VFL Spoilage",
    "Kariobangi North - VFL",
    "Kariobangi North - VFL Spoilage",
    "Ngara - VFL Spoilage",
    "Ngong Town - VFL",
    "Ngong Town - VFL Spoilage",
    "Rongai - VFL",
    "Rongai - VFL Spoilage",
    "Dagoretti - VFL Spoilage",
    "Yaya - VFL Spoilage",
    "Europe - VFL",
    "Juja - VFL",
    "Juja - VFL Spoilage",
    "Kahawa Wendani - VFL",
    "Kahawa Wendani - VFL Spoilage",
    "Kasarani - VFL",
    "Kasarani - VFL Spoilage",
    "Mwiki - VFL",
    "Mwiki - VFL Spoilage",
    "Zimmerman - VFL",
    "Thika - VFL Spoilage",
    "Thika - VFL",
    "Kahawa West - VFL Spoilage",
    "Kahawa West - VFL",
    "Zimmerman - VFL Spoilage",
    "Githurai - VFL Spoilage",
    "Githurai - VFL",
    "FishQ Bolt - VFL",
    "North America - VFL",
    "Dandora - VFL",
    "Donholm - VFL",
    "Donholm - VFL Spoilage",
    "Kangundo Road - VFL",
    "Kangundo Road - VFL Spoilage",
    "Kayole - VFL",
    "Kayole - VFL Spoilage",
    "Ruai - VFL",
    "Ruai - VFL Spoilage",
    "Umoja - VFL",
    "Umoja - VFL Spoilage",
    "Utawala - VFL",
    "Utawala - VFL Spoilage",
    "Dandora - VFL Spoilage",
    "Jogoo Road - VFL Spoilage",
    "Jogoo Road - VFL",
    "Lucky Summer - VFL Spoilage",
    "Lucky Summer - VFL",
    "Kariobangi South - VFL Spoilage",
    "Kariobangi South - VFL",
    "Oceania - VFL",
    "Makongeni - VFL",
    "Makongeni - VFL Spoilage",
    "South America - VFL",
    "Mlango Kubwa - VFL",
    "Mlango Kubwa - VFL Spoilage",
    "Test Warehouse - VFL",
    "Victory Fresh - VFL",
    "Victory Fresh - VFL Spoilage",
    "VLC - VFL",
    "VLC Branch Returns - VFL",
    "VLC Branch Spoilage - VFL",
    "VLC Deformed - VFL",
    "VLC Donations and Samples - VFL",
    "VLC Sales - VFL",
    "VLC Sales - VFL Spoilage",
    "VLC Spoilage - VFL",
    "VLC Variance - VFL",
    "VLC - Customer Direct - VFL",
    "Pwani  - VFL",
    "M/T1 Kongowea - VFL Spoilage",
    "MLC - VFL",
    "MLC Donations and Samples - VFL",
    "MLC Variance - VFL",
    "Mombasa - VFL",
    "M/T1 Bamburi Branch - VFL",
    "M/T1 Bamburi Branch - VFL Spoilage",
    "M/T1 Kisauni - VFL",
    "M/T1 Kisauni - VFL Spoilage",
    "M/T1 Kongowea - VFL",
    "M/T1 Majengo-Sakina Branch - VFL",
    "M/T1 Majengo-Sakina Branch - VFL Spoilage",
    "M/T1 Mombasa-Bombolulu  - VFL",
    "M/T1 Mombasa-Bombolulu  - VFL Spoilage",
    "M/T1 Mshomoroni Branch - VFL",
    "M/T1 Mshomoroni Branch - VFL Spoilage",
    "M/T1 Mtwapa Branch - VFL",
    "M/T1 Mtwapa Branch - VFL Spoilage",
    "M/T1 Tononoka - VFL",
    "M/T1 Tononoka - VFL Spoilage",
    "MLC Branch Returns - VFL",
    "MLC Branch Spoilage - VFL",
    "MLC Returns - VFL",
    "MLC Spoilage - VFL",
    "MLC Sales - VFL",
    "Test Warehouse 540006 - Consumables - VFL",
    "Western  - VFL",
    "Eldoret - VFL",
    "Eldoret Region - VFL",
    "Kimilili - VFL",
    "Kimilili Spoilage - VFL",
    "Mlango Nandi - VFL",
    "Nandi Hills - VFL",
    "Nandi Hills Spoilage - VFL",
    "Pipelihne Juakali Spoilage - VFL",
    "Pipeline- Juakali - VFL",
    "Webuye - VFL",
    "Webuye Spoilage - VFL",
    "Mlango Nandi Spoilage - VFL",
    "Bungoma - VFL Spoilage",
    "Bungoma - VFL",
    "Mumias - VFL",
    "Mumias - VFL Spoilage",
    "Farm - VFL",
    "FLC - VFL",
    "FLC Branch Returns - VFL",
    "FLC Branch Spoilage - VFL",
    "FLC Deformed - VFL",
    "FLC Donations and Samples - VFL",
    "FLC Spoilage - VFL",
    "FLC Variance - VFL",
    "Homa Bay Region - VFL",
    "Homabay - VFL",
    "Homabay - VFL Spoilage",
    "Mbita - VFL",
    "Mbita - VFL Spoilage",
    "Ndhiwa - VFL",
    "Rodi - VFL",
    "Rodi - VFL Spoilage",
    "Roo - VFL",
    "Roo - VFL Spoilage",
    "Sindo - VFL",
    "Sindo - VFL Spoilage",
    "Ndhiwa - VFL Spoilage",
    "Migori Region - VFL",
    "Awendo - VFL",
    "Awendo - VFL Spoilage",
    "Isebania - VFL",
    "Isebania - VFL Spoilage",
    "Kehancha - VFL",
    "Kehancha - VFL Spoilage",
    "Masara - VFL",
    "Migori - VFL",
    "Migori - VFL Spoilage",
    "Rongo - VFL",
    "Rongo - VFL Spoilage",
    "Suna East - VFL",
    "Suna East - VFL Spoilage",
    "Masara - VFL Spoilage",
    "Suneka - VFL",
    "Suneka - VFL Spoilage",
    "South Region - VFL",
    "West Region - VFL",
    "Hatchery Converted Feed - VFL",
    "Feed Warehouse Roo - VFL",
    "Hatchery Store - VFL",
    "Broodstock Warehouse - VFL",
    "Lakeshore - VFL",
    "Lake - VFL",
    "Pond - VFL",
    "Processing - VFL",
    "Fuel-Inventory - VFL",
    "Roo Farm Store - VFL",
    "Roo Trials Warehouse - VFL",
    "Farm Kitchen - VFL",
    "Kisii - Keroka - VFL Spoilage",
    "KSM - VFL",
    "Central Region - VFL",
    "East Region - VFL",
    "Kakamega Region - VFL",
    "Chavakali - VFL",
    "Chavakali - VFL Spoilage",
    "Kakamega - VFL",
    "Kakamega - VFL Spoilage",
    "Mbale - VFL",
    "Mbale - VFL Spoilage",
    "Ugunja - VFL Spoilage",
    "Ugunja - VFL",
    "Majengo - VFL Spoilage",
    "Majengo - VFL",
    "Kericho Region - VFL",
    "Awasi - VFL",
    "Awasi - VFL Spoilage",
    "Katito - VFL",
    "Katito - VFL Spoilage",
    "Muhoroni - VFL",
    "Muhoroni - VFL Spoilage",
    "Ahero - VFL Spoilage",
    "Ahero - VFL",
    "Kisii Region - VFL",
    "Kisii - Keroka - VFL",
    "Nyakoe - VFL Spoilage",
    "Nyamira - VFL",
    "Nyamira - VFL Spoilage",
    "Oyugis - VFL",
    "Oyugis - VFL Spoilage",
    "Kisii - VFL",
    "Nyakoe - VFL",
    "Kisii - VFL Spoilage",
    "Sondu - VFL Spoilage",
    "Sondu - VFL",
    "Kisumu Region - VFL",
    "Kondele - VFL",
    "Kondele - VFL Spoilage",
    "Manyatta - VFL",
    "Manyatta - VFL Spoilage",
    "Nyalenda - VFL",
    "Nyalenda - VFL Spoilage",
    "Nyamasaria - VFL",
    "Nyamasaria - VFL Spoilage",
    "KLC Sales - VFL",
    "Luanda - VFL Spoilage",
    "Luanda - VFL",
    "Siaya - VFL",
    "Siaya - VFL Spoilage",
    "W/T3 - Siaya - VFL",
    "KLC - VFL",
    "KLC Branch Returns - VFL",
    "KLC Branch Spoilage - VFL",
    "KLC Deformed - VFL",
    "KLC Donations and Samples - VFL",
    "KLC Spoilage - VFL",
    "KLC Variance - VFL",
    "North Region - VFL",
    "Otonglo - Spoilage - VFL",
    "Siaya Region - VFL",
    "Bondo - VFL",
    "Bondo - VFL Spoilage",
    "Otonglo - VFL",
    "Central - VFL",
    "Meru - VFL",
    "C/T3 - Muthara Branch - VFL",
    "C/T3 - Maua Branch - VFL",
    "C/T2 - Chuka Branch - VFL",
    "C/T3 - Chogoria Branch - VFL",
    "C/T2 - Nkubu Town Branch - VFL",
    "C/T2 - Kaaga Branch - VFL",
    "C/T2 - Meru CBD Branch  - VFL",
    "C/T2 - Meru LC - VFL",
    "Shopify Warehouse - VFL",
    "Support - VFL",
    "FishQ Procurement - VFL",
    "VF Store - VFL",
    "Broodstock Feed - VFL",
    "Hatchery Feed - VFL",
    "Feed Internal Transit - VFL",
    "Production - VFL",
    "Roo Farm On Shore - VFL",
    "Consumables in Transit - VFL",
    "Materials in transit-Other - VFL",
    "Materials in transit-Feed - VFL",
    "Import Warehouse - VFL",
    "Logistics Warehouse - VFL",
    "VLC Admin Store - VFL",
    "Fish Q VF Store - VFL",
    "Farm VF Store - VFL",
    "IT Store - VFL",
    "Farm General Store - VFL",
    "Mini-Store 3 - VFL",
    "Mini-Store 23 - VFL",
    "Mini-Store 4 - VFL",
    "Mini-Store 12 - VFL",
    "Mini-Store 19 - VFL",
    "Mini-Store 10 - VFL",
    "Mini-Store Foodstuffs - VFL",
    "Mini-Store Hatchery 1 - VFL",
    "Mini-Store Hazardous - VFL",
    "Mini-Store Lakeshore - VFL",
    "Mini-Store Net Area - VFL",
    "Mini-Store 7 - VFL",
    "Mini-Store 9 - VFL",
    "Mini-Store 5 - VFL",
    "Mini-Store 15 - VFL",
    "Mini-Store 22 - VFL",
    "Mini - Store 14 - VFL",
    "MLC Consumables Store - VFL",
    "VLC Consumables Store  - VFL",
    "Mini-Store 16 - VFL",
    "Mini-Store 14 - VFL",
    "Mini Store 24 - VFL",
    "Mini - Store Hatchery 2 - VFL",
    "KLC Consumables Store - VFL",
    "Consumables Store - VFL",
    "Mini-Store 18 - VFL",
    "All Warehouses - VG",
    "Finished Goods - VG",
    "Goods In Transit - VG",
    "Stores - VG",
    "Work In Progress - VG",
    "Farm Central Store - VFL",
    "Hatchery - VFL",
    "Kisumu Hatchery - VFL",
    "Lake Test - VFL",
    "Lakeshore Test - VFL",
    "Test 234s - VFL",
    "Test Warehouse 540001 - Biological assets - VFL",
    "Test Warehouse 540003 - Gutted Tilapia Fish - VFL",
    "Test Warehouse 540004 - Feed-Inventory - VFL",
    "Test Warehouse 540005 - Fuel-Inventory - VFL",
    "Test Warehouse 540008 - Materials in transit-Feed - VFL",
    "Test Warehouse 540009 - Materials in transit-Other - VFL",
    "VLC Feed Store - VFL",
    "Canteen  - VFL",
    "KDH 223R-HIACE - VFL",
    "3PL-CELLO-KBX 495B - VFL",
    "Rejected Warehouse - VFL",
    "Bin 1 - VFL",
]

results = []

# Pre-fetch all existing warehouse names for fast lookup
existing_warehouses = {
    row["name"]: row
    for row in frappe.db.get_all(
        "Warehouse",
        fields=["name", "is_group", "disabled", "company", "parent_warehouse", "warehouse_type"],
    )
}

# Pre-fetch warehouse names that have stock ledger entries (activity check)
active_warehouses = set(
    frappe.db.sql_list("""
        SELECT DISTINCT warehouse FROM `tabStock Ledger Entry`
        UNION
        SELECT DISTINCT warehouse FROM `tabStock Entry Detail`
        UNION
        SELECT DISTINCT s_warehouse FROM `tabStock Entry Detail` WHERE s_warehouse IS NOT NULL
    """)
)

for wh_name in warehouse_names:
    wh = existing_warehouses.get(wh_name)
    if not wh:
        results.append({
            "warehouse": wh_name,
            "exists": "NO",
            "disabled": "N/A",
            "is_group": "N/A",
            "parent_warehouse": "N/A",
            "has_activity": "N/A",
            "suggested_action": "REMOVE — does not exist in ERPNext",
        })
        continue

    has_activity = "YES" if wh_name in active_warehouses else "NO"
    is_group = int(wh.get("is_group", 0))
    disabled = int(wh.get("disabled", 0))

    action_parts = []
    if disabled:
        action_parts.append("DISABLED")
    if is_group:
        action_parts.append("GROUP PARENT")
    if has_activity == "NO" and not is_group:
        action_parts.append("ZERO ACTIVITY")
    if not action_parts:
        action_parts.append("OK — functional")

    results.append({
        "warehouse": wh_name,
        "exists": "YES",
        "disabled": "YES" if disabled else "NO",
        "is_group": "YES" if is_group else "NO",
        "parent_warehouse": wh.get("parent_warehouse", ""),
        "has_activity": has_activity,
        "suggested_action": " | ".join(action_parts),
    })

# Build CSV output for easy copy/paste
csv_lines = ["Warehouse,Exists,Disabled,Is Group,Parent Warehouse,Has Activity,Suggested Action"]
for r in results:
    csv_lines.append(
        '"{}","{}","{}","{}","{}","{}","{}"'.format(
            r["warehouse"], r["exists"], r["disabled"], r["is_group"],
            r["parent_warehouse"], r["has_activity"], r["suggested_action"]
        )
    )

print("\n".join(csv_lines))

# Also print summary counts
non_existent = [r for r in results if r["exists"] == "NO"]
disabled = [r for r in results if r["disabled"] == "YES"]
groups = [r for r in results if r["is_group"] == "YES"]
zero_activity = [r for r in results if r["has_activity"] == "NO" and r["exists"] == "YES" and r["is_group"] == "NO"]

print("\n\n=== SUMMARY ===")
print(f"Total in your list: {len(warehouse_names)}")
print(f"Non-existent in ERPNext: {len(non_existent)}")
print(f"Disabled: {len(disabled)}")
print(f"Group parents: {len(groups)}")
print(f"Functional but zero stock activity: {len(zero_activity)}")
print(f"Likely functional (exists, not disabled, not group, has activity): {len(warehouse_names) - len(non_existent) - len(disabled) - len(groups) - len(zero_activity)}")
